name: Ticketmania â€“ PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push PROD image
        run: |
          docker build \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:prod-${GITHUB_SHA} \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            .

          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:prod-${GITHUB_SHA}
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
