name: Ticketmania â€“ PROD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-prod:
    runs-on: ubuntu-latest
    environment: production

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}  
      ECR_REGISTRY: ${{ vars.ECR_REGISTRY }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.ECR_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.ECR_ACCESS_SECRET }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build & push PROD image
        run: |
          docker build \
            -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:prod-${GITHUB_SHA} \
            -t ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest \
            .

          docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:prod-${GITHUB_SHA}
          docker push ${{ env.ECR_REGISTRY }}/${{ env.IMAGE_NAME }}:latest