name: Ticketmania â€“ UAT

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-uat:
    runs-on: ubuntu-latest
    environment: uat

    env:
      IMAGE_NAME: ${{ vars.IMAGE_NAME }}
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & push UAT image
        run: |
          docker build \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:uat-${GITHUB_SHA} \
            -t ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:uat \
            .

          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:uat-${GITHUB_SHA}
          docker push ${{ env.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:uat
